Powiedziałeś(-aś):
name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install client dependencies
        working-directory: promptsentry.client
        run: npm ci

      - name: Build Angular app
        working-directory: promptsentry.client
        run: npm run build -- --output-path=../PromptSentry.Server/wwwroot

      - name: Restore .NET dependencies
        run: dotnet restore PromptSentry.Server/PromptSentry.Server.csproj

      - name: Build .NET project
        run: dotnet build PromptSentry.Server/PromptSentry.Server.csproj --configuration Release --no-restore

      - name: Publish .NET app
        run: dotnet publish PromptSentry.Server/PromptSentry.Server.csproj --configuration Release --output ./publish --no-build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
